### ISSUE TITLE
Run tests from Playground Exercises 

### ISSUE THREAD

**Issue by ArielUmansky** [mumuki/mumuki-ruby-runner#27]
I'd like the feature of running ruby tests (Minitest) from a Playground kind of exercise. 

I imagine something like this: 

![image](https://user-images.githubusercontent.com/1649905/27294806-3743d4f4-54f1-11e7-93c1-385899a2c765.png)

The underlying idea is to give the students a grasp of the normal flow of unit test development.

**Comment by flbulgarelli** [comment]
I am working on this. However, allowing user to parameterize the test filename add some - unnecessary, IMHO -  complexity. What about just asking the user to run `rake test` @ArielUmansky ?

**Comment by flbulgarelli** [comment]
@ArielUmansky  please check https://github.com/mumuki/mumuki-minitest-runner/pull/1

**Comment by ArielUmansky** [comment]
Yeah ok.. I'm fine with that. The user will always run all the tests but I think it's good enough. 

We could write in some corollary that they should be able to run individual tests, files and folders anyway..

Thanks!
