### ISSUE TITLE
Support expectations

### ISSUE THREAD

**Issue by flbulgarelli** [mumuki/mumuki-ruby-runner#4]
Some inspections should support are:
- HasMethod:x  whether the target class declared the given method
- HasClass whether the target class exists
- HasVariable whether the target variable exists
- HasUsage:x whether the target method uses the given method
- HasArity:x whether the target method has the given arity

The inspector may be implemented as a simple rspec test, since most if not all those checks may be implemented at runtime

**Comment by bossiernesto** [comment]
Most of the functionalities can be tested at runtime, other strategy is to have an inspector for compile and specific code declarations at compiling time and other on runtime if the method definitions are done dynamically via a define_method.

**Comment by flbulgarelli** [comment]
See https://github.com/flbulgarelli/rb-inspector

It is currently ast-based. But ir could incorporate dynamic checks.

**Comment by flbulgarelli** [comment]
Development of this feature has moved to https://github.com/mumuki/mulang-ruby

**Comment by flbulgarelli** [comment]
Fixed #28
